version: "3.8"
services:
 db:
  image: postgis/postgis:13-master
  environment:
   - POSTGRES_USER=$DB_ADMIN_USR
   - POSTGRES_PASSWORD=$DB_ADMIN_PWD
  ports:
   - 5432:$DB_PORT
  volumes:
   - ./db/data:/var/lib/postgresql/data
  restart: always
 api:
  depends_on:
   - db
  build: ./api
  environment:
   - NODE_ENV=$API_NODE_ENV
   - PORT=$API_PORT
   - PGHOST=db
   - PGPORT=$DB_PORT
   - PGDATABASE=$DB_NAME
   - PGUSER=$DB_API_USR
   - PGPASSWORD=$DB_API_PWD
  ports:
   - $API_PORT:$API_PORT
  volumes:
   - ./api:/app
   - /app/node_modules
 ui:
  build: ./ui
  environment:
   - NODE_ENV=$UI_NODE_ENV
   - REACT_APP_API_URL
   - REACT_APP_MAPBOX_ACCESS_TOKEN
  ports:
   - 3000:$UI_PORT
  volumes:
   - ./ui:/app
   - /app/node_modules
  stdin_open: true
