version: "3"
services:
 db:
  image: postgis/postgis:13-master
  environment:
   - POSTGRES_USER=$ADMIN_USER
   - POSTGRES_PASSWORD=$ADMIN_USER_PWD
  ports:
   - 5432:$DB_PORT
  volumes:
   - ./data:/var/lib/postgresql/data
  restart: always
 api:
  image: nicodes/ctcalc-api
  depends_on:
   - db
  environment:
   - NODE_ENV=$API_NODE_ENV
   - PORT=$API_PORT
   - PGHOST=db
   - PGPORT=$DB_PORT
   - PGDATABASE=$DB_NAME
   - PGUSER=$API_USER
   - PGPASSWORD=$API_USER_PWD
  ports:
   - $API_PORT:$API_PORT
 ui:
  image: nginx
  ports:
   - 80:80
  volumes:
   - ./ui/build:/usr/share/nginx/html
