version: "3.8"
services:
 db:
  image: postgis/postgis:13-master
  environment:
   - POSTGRES_USER=$ADMIN_USER
   - POSTGRES_PASSWORD=$ADMIN_USER_PWD
   - API_USER=$API_USER
   - API_USER_PWD=$API_USER_PWD
  ports:
   - $DB_PORT:$DB_PORT
  volumes:
   - ./db/data:/var/lib/postgresql/data
  restart: always
  command: -p $DB_PORT
 api:
  depends_on:
   - db
  build: ./api
  environment:
   - NODE_ENV=$ENV
   - PORT=$API_PORT
   - PGHOST=db
   - PGPORT=$DB_PORT
   - PGDATABASE=$DB_NAME
   - PGUSER=$API_USER
   - PGPASSWORD=$API_USER_PWD
  ports:
   - $API_PORT:$API_PORT
  volumes:
   - ./api:/app
   - /app/node_modules
 ui:
  build: ./ui
  environment:
   - NODE_ENV=$ENV
   - PORT=$UI_PORT
   - REACT_APP_API_HOST
   - REACT_APP_MAPBOX_ACCESS_TOKEN
  ports:
   - $UI_PORT:$UI_PORT
  volumes:
   - ./ui:/app
   - /app/node_modules
  stdin_open: true
